### ISSUE TITLE
challenge-sum-of-squares

### ISSUE THREAD

**Issue by jiaosenvip** [labex-labs/scenarios#400] opened 2023-04-13 02:56 UTC
> **Please read [For Newbie](https://github.com/labex-labs/scenarios/issues/18) first. 请先阅读 [新手须知](https://github.com/labex-labs/scenarios/issues/18)。**

## Basic

> Basic information about the scenario, which can be changed if required.
> 实验/挑战的基本信息，如有需要，可以修改。

- **Suggest Title 建议标题**: Sum of Squares
- **Suggest Steps 建议步骤数**: 1
- **Suggest Image 建议环境**: `webide-ubuntu:2204`

## Sources

> Issues has provided the material; the part not provided must be completed by the author.
> Issues 已经提供了材料；没有提供的部分由作者自行补充完成。

- [x] Full Text 正文内容
- [x] Reference Answers 参考答案
- [x] Verify Script 检测脚本

## Skills

> Suggested skills to include can be modified as needed. **The main skill points that should be included in this section are bolded**. From [Skills Tree](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp).
> 建议包括的 Skills ID，可以根据需要增删。**本章节应包含的主要技能点已加粗**，技能点来自 [技能树](https://labex-dev.feishu.cn/base/bascnNz4Nqjqgqm1Nm5AYke6xxb?table=tblV5pGIsGZMxmE9&view=vewZpkLWRp)

- **`python/function_basic`**
- **`python/for_loop`**

**Comment by jiaosenvip** [comment] 2023-04-13 02:57
# Sum of Squares

## Introduction 

This challenge will have you practice writing functions in Python.

## Problem Description

Write a function that calculates the sum of the squares of the first n natural numbers.

## Requirements

1. Define a function named `sum_of_squares` that takes an integer n as input.
2. The function should return the sum of the squares of the numbers from 1 to n.
3. For example, sum_of_squares(3) should return 1^2 + 2^2 + 3^2 = 14.

## Example Usage

```python
sum_of_squares(3) # Returns 14
sum_of_squares(10) # Returns 385
```

## Code Template

```python
def sum_of_squares(n):
    """Calculates the sum of the squares of numbers from 1 to n."""
    sum = 0
    # Your code here
```   

## Summary

This challenge had you practice writing a simple function in Python that uses a loop to accumulate a sum. 

## Answer

```python
def sum_of_squares(n):
    """Calculates the sum of the squares of numbers from 1 to n."""
    sum = 0
    for i in range(1, n + 1):
        sum += i * i
    return sum
```

## Unittest.

```python
import unittest

def sum_of_squares(n):
    """Calculates the sum of the squares of numbers from 1 to n."""
    sum = 0
    for i in range(1, n + 1):
        sum += i * i
    return sum

class TestSumOfSquares(unittest.TestCase):
    def test_sum_of_squares(self):
        self.assertEqual(sum_of_squares(3), 14)
        self.assertEqual(sum_of_squares(10), 385)
        self.assertEqual(sum_of_squares(0), 0)

if __name__ == '__main__': 
    unittest.main()
```

**Comment by huhuhang** [comment] 2023-04-13 05:59
Duplicate of #

**Closed by huhuhang** 2023-04-13 05:59 UTC
Labels: Python, New, Challenge, Beginner, Pending Review
